# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      # TODO Cache TexLive dependencies based on texlive.profile file hash

      # Runs a single command using the runners shell
      - name: Install tex-live
        run: |
          PROJECTDIR=$(pwd)
          cd /tmp && wget http://ftp.fau.de/ctan/systems/texlive/tlnet/install-tl-unx.tar.gz
          tar -xvzf install-tl-unx.tar.gz
          cd install-tl-*
          chmod +x install-tl
          sudo ./install-tl --profile=$PROJECTDIR/texlive.profile
          PATH=/usr/local/texlive/2017/bin/x86_64-linux:$PATH
          pdflatex -v
          cd $PROJECTDIR
          
        

      # Runs a set of commands using the runners shell
      - name: Run build script
        run: bash tests/testall.sh
